# -*- coding: utf-8 -*-
"""Verify block params-count for a level zip package.

Part of the level-generator skill toolchain. Every generated/modified level
must pass this check before delivery (see .cursor/skills/level-generator/SKILL.md
section 0.6 step 1).

What it checks:
  For every block node (any dict with a "define" key) inside the package's
  .ws file, the number of entries in sections[0].params must match the
  registry entry scripts/params_registry.json.

Registry classification:
  - strict:   one params-count observed across >=3 sightings in reference
              packages. Mismatch => FAIL.
  - variable: multiple params-counts seen. Mismatch => WARN.
  - rare:     fewer than 3 sightings. Not hard-enforced (WARN only).

The registry is generated by scripts/build_params_registry.py from the
reference packages under 参考-extracted/. Regenerate it whenever new
block types appear in released levels.

Usage:
  python scripts/verify_blocks.py <zip_path>
  python scripts/verify_blocks.py output/modify/xxx-v2.zip

Exit codes:
  0  PASS (no strict errors)
  2  FAIL (one or more strict errors)
  3  usage / IO error
"""
from __future__ import annotations

import json
import sys
import zipfile
from collections import Counter
from pathlib import Path

REGISTRY_PATH = Path(__file__).with_name("params_registry.json")


def iter_blocks(node, path="/"):
    """Yield (json-pointer-style path, block-dict) for every block found in a scene subtree.

    A "block" is any dict that has a "define" key. We recurse through:
      - scene nodes' children[]
      - BlockScript.fragments[].head and its nested structure
      - BlockScript.myblocks[].fragment.head
      - block sections[i].children[] and sections[i].params[].val (type=block)
    """
    if not isinstance(node, dict):
        return

    # Case 1: a scene node (type present, optional children, optional BlockScript-specific fields)
    node_type = node.get("type")
    if node_type is not None:
        if node_type == "BlockScript":
            frags = node.get("fragments")
            if frags is None and "blockScript" in node:
                # Wrong "blockScript:{fragments}" wrapper format — yield error sentinel then still traverse
                yield f"{path}[FORMAT_ERROR]", {"define": "__BLOCKSCRIPT_WRAPPER_INVALID__", "sections": []}
                frags = (node.get("blockScript") or {}).get("fragments", [])
            for i, frag in enumerate(frags or []):
                head = frag.get("head") or (frag if "define" in frag else None)
                if head:
                    yield from iter_blocks(head, f"{path}fragments[{i}]/head")
            for i, mb in enumerate(node.get("myblocks", []) or []):
                frag = mb.get("fragment") if isinstance(mb, dict) else None
                if frag and frag.get("head"):
                    yield from iter_blocks(
                        frag["head"], f"{path}myblocks[{i}]/fragment/head"
                    )
        for i, c in enumerate(node.get("children", []) or []):
            yield from iter_blocks(c, f"{path}children[{i}]/")
        return

    # Case 2: a block (has "define")
    if "define" in node:
        yield path.rstrip("/"), node
        for si, sec in enumerate(node.get("sections", []) or []):
            for pi, p in enumerate(sec.get("params", []) or []):
                if isinstance(p, dict) and p.get("type") == "block":
                    val = p.get("val")
                    if val:
                        yield from iter_blocks(
                            val, f"{path}sections[{si}]/params[{pi}]/val"
                        )
            for ci, c in enumerate(sec.get("children", []) or []):
                yield from iter_blocks(
                    c, f"{path}sections[{si}]/children[{ci}]/"
                )


def load_registry(path: Path) -> dict:
    if not path.exists():
        print(
            f"[FAIL] registry missing: {path}\n"
            f"       run: python scripts/build_params_registry.py",
            file=sys.stderr,
        )
        raise SystemExit(3)
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("entries", {})


def load_ws_from_zip(zip_path: Path) -> dict:
    with zipfile.ZipFile(zip_path, "r") as zf:
        ws_names = [n for n in zf.namelist() if n.lower().endswith(".ws")]
        if not ws_names:
            raise SystemExit(f"[FAIL] no .ws inside {zip_path}")
        if len(ws_names) > 1:
            print(f"[warn] multiple .ws in zip, using the first: {ws_names[0]}")
        with zf.open(ws_names[0]) as f:
            raw = f.read().decode("utf-8")
    return json.loads(raw)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python scripts/verify_blocks.py <zip_path>", file=sys.stderr)
        return 3

    zip_path = Path(argv[1])
    if not zip_path.exists():
        print(f"[FAIL] zip not found: {zip_path}", file=sys.stderr)
        return 3

    print(f"Verifying: {zip_path}")
    print(f"Registry : {REGISTRY_PATH.name}")

    registry = load_registry(REGISTRY_PATH)
    data = load_ws_from_zip(zip_path)
    scene = data.get("scene")
    if not scene:
        print("[FAIL] ws has no 'scene'")
        return 2

    errors: list[str] = []
    warns: list[str] = []
    count_by_define: Counter = Counter()

    for bpath, blk in iter_blocks(scene):
        define = blk.get("define")
        count_by_define[define] += 1

        # Format-error sentinel injected by iter_blocks — hard FAIL
        if define == "__BLOCKSCRIPT_WRAPPER_INVALID__":
            errors.append(
                f"{bpath}: BlockScript node uses wrong 'blockScript:{{fragments}}' wrapper "
                f"instead of top-level 'fragments' — engine will silently ignore all scripts"
            )
            continue

        sections = blk.get("sections", [])
        actual = len(sections[0].get("params", [])) if sections else 0

        entry = registry.get(define)
        if entry is None:
            warns.append(
                f"{bpath} {define}: not in registry (actual params={actual})"
            )
            continue

        kind = entry.get("kind")
        expect = entry.get("expect")

        if kind == "strict":
            if actual != expect:
                errors.append(
                    f"{bpath} {define}: expected {expect} params, got {actual}"
                )
        elif kind == "variable":
            if actual != expect:
                dist = entry.get("distribution", {})
                seen = ", ".join(f"{k}={v}" for k, v in sorted(dist.items()))
                warns.append(
                    f"{bpath} {define}: uncommon params-count {actual} "
                    f"(dominant={expect}; seen in reference: {seen})"
                )
        # kind == "rare": skip (warn would be noisy)

    print(f"\n=== Top 25 block types ===")
    for define, n in count_by_define.most_common(25):
        entry = registry.get(define)
        exp = entry.get("expect") if entry else "?"
        kind = entry.get("kind") if entry else "unregistered"
        print(f"  {define:<30} x{n:<4} expect={exp} ({kind})")

    if warns:
        print(f"\n=== Warnings ({len(warns)}) ===")
        for w in warns[:20]:
            print(f"  - {w}")
        if len(warns) > 20:
            print(f"  ... {len(warns) - 20} more")

    print()
    if errors:
        print(f"[FAIL] {len(errors)} strict params-count error(s):")
        for e in errors:
            print(f"  - {e}")
        return 2

    print("[PASS] all registered blocks have correct params count")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
